name: Build & Deploy GitHub Pages with LFS

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up Ruby (for Jekyll sites)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.x'
          bundler-cache: true      # caches gems between runs

      - name: Install dependencies
        run: |
          bundle install   # for Jekyll
          # or npm install # for Node static sites

      - name: Build site
        run: |
          bundle exec jekyll build   # Jekyll
          # or npm run build         # other static generators

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site        # or your `public/` folder
          publish_branch: gh-pages
